### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by zbarnes757**

### CODE REVIEW

**Comment by gangstead** [comment]
Is this repo dead?

**Comment by mathewdgardner** [comment]
Hardly, just that the node coveralls doesn't work well with circleci out of the box. I've tried to fix it but I'll need you to rebase to see if it worked, @zbarnes757.

**Comment by zbarnes757** [comment]
nope. Still fails. How can I contribute to your open source project and make it better if you are hindering me with silly tools???

**Comment by mathewdgardner** [comment]
You got passed the coveralls problem but now cirlce isn't providing the env var for your build. I went ahead and just turned coveralls off for branches. Try again.

**Comment by zbarnes757** [comment]
I give up. The notoriety just isn't worth it.

**Comment by mathewdgardner** [comment]
I turned it off and you're giving up?!

**Comment by zbarnes757** [comment]
it failed again!

**Comment by gangstead** [comment]
Is there another project that picked up where this one left off?

**Comment by zbarnes757** [comment]
@gangstead https://github.com/elixir-ecto/ecto

**Comment by mathewdgardner** [comment]
@zbarnes757 somehow this is building under your own circle and not mine like it did when it first failed and this is why you aren't getting the coveralls token and also why it isn't skipping coveralls. It will skip coveralls if in circle the branch isn't master. Before it would be pull/\* on my circle but your build is on master under your own circle.

I imagine it has something to do with the rebase. Circle docs say that if you have your own circle yml or enable building on your own that it will not build the forks for me.

**Comment by mathewdgardner** [comment]
@zbarnes757 go to the circle build that failed and go to the project settings and stop building project. Then I'll kick it off from my side of circle.

**Comment by mathewdgardner** [comment]
@zbarnes757 what did you do to get it to pass?

**Comment by zbarnes757** [comment]
I created my own coveralls account and added my repo token to circle.

giphy

**Pull request merged**
